#First, Let us load the Tiddyverse Package for cleaning.
library(tidyverse)
#Next, Let us read our dataset into R.
df <- read_csv("~/desktop/telecom.csv")
head(df)
#By using the R function 'glimpse', we can determine what type of variables we are dealing with.
glimpse(df)
# With glimpse, we came up with a conclusion that our dataset has 10 obs and 5 variables.
# DATA MANIPULATION
# Now that we’ve taken a quick look to become familiar with the data, let’s go over some basic data manipulation.
# For instance, if we want to only look for customers that churned, we filter the churn value 'YES'using the filter function in Dplyr.
df1 <- filter(df, Churn=='yes')
# Maybe we also want to select the customerID and Totalcharges columns.We can use the select function for this.
select(df1,customerID, TotalCharges)
# Standard Missing Values.(The type of missing values that R recognize)
# Dealing with missing values. Let us determine how many missing values are found in the variable 'MonthlyCharges'.
# We us the Distinct function to select distinct values or unique values in a column or table.
is.na(df$MonthlyCharges)
distinct(df,MonthlyCharges)
# Line 18 can also be generated by the following code. "Df %>%" (Hit return) then "Distinct(monthlyCharges)".
# If we want to get a quick count of distinct values we can use the summarise function.
df %>%
  summarise(n = n_distinct(MonthlyCharges))
# Also to determine the total number is missing values in the 'MonthlyCharges' variable goes as follow.
sum(is.na(df$MonthlyCharges))
# For instance, if we want to do multiple things at once; that is we want to count unique values, missing values, and calculate the median a particular variable.
df %>%
  summarise(n=n_distinct(MonthlyCharges),
            na=sum(is.na(MonthlyCharges)),
                   med=median(MonthlyCharges, na.rm = TRUE))
# Now that we have identified the missing values, let us replace them by the median using the mutate function from Dplyr.
df <- df %>%
  mutate(MonthlyCharges
         =replace(MonthlyCharges,
                  is.na(MonthlyCharges),
                  median(MonthlyCharges, na.rm = TRUE)))
df
# Remember, missing values in continuous/numerical variables are replaced by the median of that paricular variable.
# Whereas NA in categorical variables are replaced by the mode. 
# Non-standard Missing Values.(The Type of missing values R does not recognize such as 'na' and 'N/A'.
# Looking at missing values in TotalCharges.
is.na(df$TotalCharges)
# OR
sum(is.na(df$TotalCharges))
# Or let us use the summarise function to see how many missing values are there.
df %>%
  summarise(count=sum(is.na(TotalCharges)))
# R does not recognize both 'na' and 'N/A' as missing values, therefore we will replace them with 'NA' using the mutate function.
df <- df %>%
  mutate(TotalCharges = replace(TotalCharges, TotalCharges == "na", NA)) %>%
           mutate(TotalCharges = replace(TotalCharges, TotalCharges == "N/A", NA))
df
# Let us take another look at how many missing values.
sum(is.na(df$TotalCharges))
# if we use the 'glimpse' function again, the totalcharges variable is considered to be a character/categorical variable. But it is not.
# Let us change it to numerical.
df$TotalCharges <- as.numeric(df$TotalCharges)
glimpse(df$TotalCharges)
# Finally let us replace the missing values with the median.
df <- df %>%
  mutate(TotalCharges
         =replace(TotalCharges,
                  is.na(TotalCharges),
                  median(TotalCharges, na.rm = TRUE)))
df
# There is numerous other ways to represent missing data: Such as using '--' or Blank spaces. What do we do in those instances?
# Let us consider the 'PaymentMethod' variable for example.
is.na(df$PaymentMethod)
# R only considers the empty space (in this case NA) as the missing value. We will replace '--' by NA using mutate.
df <- df %>%
  mutate(PaymentMethod = replace(PaymentMethod, PaymentMethod == "--", NA))
df
# So far, when dealing with missing values in the numerical (continuous) variables, we have replaced those missing values with the median.
# In this case, since we are dealing with character strings in the PaymentMethod variable, there is no median to replace those missing values with.
# Here, we will convert all missing values (NAs) to a new category called 'Unavailable'.
# Replace all NAs with 'Unavailable'
df %>%
  mutate(PaymentMethod = replace(PaymentMethod, is.na(PaymentMethod), "Unavailable"))
# Now we can say that our dataset is completely clean!
# There are instances where missing values from character variables are thrown out. 
## Thank you for your Patience and Hard work!!!
